# fly.toml app configuration file generated for dawn-sun-1269 on 2023-06-20T04:23:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dawn-sun-1269"
primary_region = "atl"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
